In [ ]:
import numpy as np

In [ ]:
l = [10, 20, 30, 40, 50]
new = np.array(l)
new
type(new)

numpy.ndarray

In [ ]:
l = [
    [1,2,3],
    [4,5,6]
]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
l = [12,34,2,4,66]
new = np.array(l)
if type(new) == np.ndarray:
  print('Yess')

Yess


In [ ]:
l = np.array([1.,2., 3.,4.])
l
l.dtype

dtype('float64')

In [ ]:
l = [['A','B','C'], ['D','E','F'], ['G','H','I']]
np.array(l)

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I']], dtype='<U1')

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
l = '5' * 8
a = list(l)
n = np.array([a])
print(n.dtype)

<U1


In [ ]:
n = np.full(8,5)
n.dtype

dtype('int64')

In [ ]:
n = np.arange(5,51,5)

In [ ]:
n

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
n = np.linspace(0,1,12)
n

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [ ]:
arr = np.random.randint(1,101, size=10)
arr

array([95, 14, 80, 28, 45, 77, 92, 13, 99, 13])

In [ ]:
arr = np.random.randint(1,10, size = (4,4))
arr

array([[6, 1, 9, 3],
       [9, 1, 6, 3],
       [4, 7, 8, 6],
       [7, 3, 7, 8]])

In [ ]:
import random
x =  np.random.rand(20)
x

array([0.05622524, 0.68452675, 0.09924718, 0.64857009, 0.9380754 ,
       0.04314671, 0.59975413, 0.69744729, 0.00285223, 0.73766907,
       0.48760344, 0.37456555, 0.24157574, 0.20822772, 0.78038144,
       0.00245845, 0.41878132, 0.41792001, 0.97490946, 0.19720043])

In [ ]:
n = np.random.randint(1,100, size = 10)
n

array([41, 97, 26, 17, 81, 47, 72, 11, 94, 42])

In [ ]:
n = np.random.randint(1,9, size=(4,4))
n

array([[5, 7, 5, 1],
       [5, 1, 8, 1],
       [6, 3, 3, 1],
       [3, 7, 2, 5]])

In [ ]:
a = np.random.random(size=20)
a

array([0.81479499, 0.09909258, 0.90968192, 0.17480625, 0.03665782,
       0.07741915, 0.47633723, 0.11402838, 0.54942978, 0.13662848,
       0.12815484, 0.63049238, 0.99459902, 0.40811885, 0.45194473,
       0.79784028, 0.29927271, 0.44575564, 0.13494817, 0.442427  ])

In [ ]:
a = np.random.randint(1,45, size=(3,5))
largest = np.max(a)
small = np.min(a)
Avg = np.mean(a)

print(a, largest, small, Avg)

[[44 12 18 17  3]
 [ 7 27 23 23 32]
 [36 39 37 37  4]] 44 3 23.933333333333334


In [ ]:
arr = np.random.randint(1,100, (4,5))
print(arr.ndim, arr.shape,arr.size,arr.dtype,arr.itemsize)

2 (4, 5) 20 int64 8


In [ ]:
arr = np.array([1,2,3])
print(arr.ndim, arr.shape)

1 (3,)


In [ ]:
arr = np.array([[1,2], [3,4]])
print(arr.ndim, arr.shape)

2 (2, 2)


In [ ]:
arr = np.array([
    [[1,2]],
    [[3,4]],
    [[4,5]]
])
print(arr, arr.ndim, arr.shape)

[[[1 2]]

 [[3 4]]

 [[4 5]]] 3 (3, 1, 2)


In [ ]:
arr = np.random.random((5,3))
arr.size

15

In [ ]:
arr = np.random.random((7,5))
print(f'size of array: {arr.size}, \nMemory size of 1 element in array {arr.itemsize} \nTotal Memory size of array: {arr.size * arr.itemsize}')

size of array: 35, 
Memory size of 1 element in array 8 
Total Memory size of array: 280


In [ ]:
a = np.arange(1,25)
print(f'{a.reshape(4,6)}, \n\n{a.reshape(6,4)},\n\n {a.reshape(2,12)}')

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]], 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]],

 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [ ]:
arr = np.random.random((6,5))
arr

array([[0.11083194, 0.89865195, 0.80306849, 0.94232532, 0.56073532],
       [0.57878076, 0.84636605, 0.45916232, 0.39499004, 0.74156414],
       [0.29970185, 0.49961134, 0.03401644, 0.02800636, 0.74105546],
       [0.05669481, 0.26428612, 0.50016846, 0.68571278, 0.16885865],
       [0.78337786, 0.07089863, 0.07725619, 0.92787603, 0.89423114],
       [0.06448974, 0.48431699, 0.22144726, 0.49389254, 0.49196303]])

In [ ]:
arr.flatten()

array([0.11083194, 0.89865195, 0.80306849, 0.94232532, 0.56073532,
       0.57878076, 0.84636605, 0.45916232, 0.39499004, 0.74156414,
       0.29970185, 0.49961134, 0.03401644, 0.02800636, 0.74105546,
       0.05669481, 0.26428612, 0.50016846, 0.68571278, 0.16885865,
       0.78337786, 0.07089863, 0.07725619, 0.92787603, 0.89423114,
       0.06448974, 0.48431699, 0.22144726, 0.49389254, 0.49196303])

In [ ]:
new_arr = arr.reshape(3,10)
new_arr

array([[0.11083194, 0.89865195, 0.80306849, 0.94232532, 0.56073532,
        0.57878076, 0.84636605, 0.45916232, 0.39499004, 0.74156414],
       [0.29970185, 0.49961134, 0.03401644, 0.02800636, 0.74105546,
        0.05669481, 0.26428612, 0.50016846, 0.68571278, 0.16885865],
       [0.78337786, 0.07089863, 0.07725619, 0.92787603, 0.89423114,
        0.06448974, 0.48431699, 0.22144726, 0.49389254, 0.49196303]])

In [ ]:
# print(f"reshape :{new_arr.reshape} \nflatten: {new_arr.flatten}, \n{new_arr.ravel}")
print("reshape:")
print(new_arr.reshape(5, 6))

print("\nflatten:")
print(new_arr.flatten())

print("\nravel:")
print(new_arr.ravel())

reshape:
[[0.11083194 0.89865195 0.80306849 0.94232532 0.56073532 0.57878076]
 [0.84636605 0.45916232 0.39499004 0.74156414 0.29970185 0.49961134]
 [0.03401644 0.02800636 0.74105546 0.05669481 0.26428612 0.50016846]
 [0.68571278 0.16885865 0.78337786 0.07089863 0.07725619 0.92787603]
 [0.89423114 0.06448974 0.48431699 0.22144726 0.49389254 0.49196303]]

flatten:
[0.11083194 0.89865195 0.80306849 0.94232532 0.56073532 0.57878076
 0.84636605 0.45916232 0.39499004 0.74156414 0.29970185 0.49961134
 0.03401644 0.02800636 0.74105546 0.05669481 0.26428612 0.50016846
 0.68571278 0.16885865 0.78337786 0.07089863 0.07725619 0.92787603
 0.89423114 0.06448974 0.48431699 0.22144726 0.49389254 0.49196303]

ravel:
[0.11083194 0.89865195 0.80306849 0.94232532 0.56073532 0.57878076
 0.84636605 0.45916232 0.39499004 0.74156414 0.29970185 0.49961134
 0.03401644 0.02800636 0.74105546 0.05669481 0.26428612 0.50016846
 0.68571278 0.16885865 0.78337786 0.07089863 0.07725619 0.92787603
 0.89423114 0.06448974 

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

flat = arr.flatten()
rav = arr.ravel()

flat[0] = 100
print(arr)
# Still
# [[1 2]
#[3 4]]

rav[0] = 200
print(arr)
# Now
# [[200   2]
# [  3   4]]

[[1 2]
 [3 4]]
[[200   2]
 [  3   4]]


Class 2

In [ ]:
import numpy as np
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr[:5]

array([1, 2, 3, 4, 5])

In [ ]:
arr[-1:-6:-1]

array([20, 19, 18, 17, 16])

In [ ]:
arr[5:13]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
arr[::3]

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
arr[-1::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [ ]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[3:7] = 100
arr

array([  1,   2,   3, 100, 100, 100, 100,   8,   9,  10])

In [ ]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
matrix[0]

array([1, 2, 3, 4, 5])

In [ ]:
matrix[-1]

array([21, 22, 23, 24, 25])

In [ ]:
matrix[:,0]

array([ 1,  6, 11, 16, 21])

In [ ]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
matrix[:, 4]

array([ 5, 10, 15, 20, 25])

In [ ]:
matrix[2, 2]

np.int64(13)

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr[:2, :2]

array([[1, 2],
       [6, 7]])

In [ ]:
arr[2:, 2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [ ]:
arr[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr[:, 1]

array([ 2,  7, 12, 17, 22])

In [ ]:
arr[3]

array([16, 17, 18, 19, 20])

In [ ]:
arr = np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
arr[1:5]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr[:, 1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22],
       [26, 27, 28],
       [32, 33, 34]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
arr[::2]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr[:, ::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
arr[::-1]

array([[31, 32, 33, 34, 35, 36],
       [25, 26, 27, 28, 29, 30],
       [19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [ ]:
arr[::-1, ::-1]

array([[36, 35, 34, 33, 32, 31],
       [30, 29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20, 19],
       [18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [ ]:
arr = np.array([12, 5, 18, 27, 9, 33, 41])
# greaterthen = arr > 20
# arr = arr[greaterthen]
arr

array([12,  5, 18, 27,  9, 33, 41])

In [ ]:
# evenn = arr%2 == 0
# arr = arr[evenn]
# arr

In [ ]:
between = (arr <=30) & (arr >= 10)
arr = arr[between]
arr

array([12, 18, 27])

In [ ]:
arr = np.random.randint(1,50,20)
arr

array([41, 49, 19, 29,  3, 44, 39, 41, 18, 30,  6, 31, 11, 24, 38, 44, 34,
       10, 48, 13])

In [ ]:
evenn = arr%2==0
arr[evenn] = 0
arr

array([41, 49, 19, 29,  3,  0, 39, 41,  0,  0,  0, 31, 11,  0,  0,  0,  0,
        0,  0, 13])

In [ ]:
great = arr > 30
arr[great] = 999
arr

array([999, 999,  19,  29,   3,   0, 999, 999,   0,   0,   0, 999,  11,
         0,   0,   0,   0,   0,   0,  13])

In [ ]:
marks = np.array([85, -1, 92, 76, -1, 68, 99, -1])
marks

array([85, -1, 92, 76, -1, 68, 99, -1])

In [ ]:
zer = marks < 0
marks[zer] = 0
marks

array([85,  0, 92, 76,  0, 68, 99,  0])

In [ ]:
valid_marks = marks>=0
marks= marks[valid_marks]
marks

array([85,  0, 92, 76,  0, 68, 99,  0])

In [ ]:
sales = np.random.randint(100,1000,(7,5))
sales

array([[131, 632, 546, 266, 976],
       [568, 230, 535, 413, 352],
       [874, 918, 630, 139, 312],
       [921, 929, 384, 427, 277],
       [346, 399, 205, 692, 855],
       [588, 843, 566, 260, 174],
       [379, 687, 664, 553, 185]])

In [ ]:
sales[2]

array([874, 918, 630, 139, 312])

In [ ]:
sales[:, 1]

array([632, 230, 918, 929, 399, 843, 687])

In [ ]:
sales[1:5,:3]

array([[568, 230, 535],
       [874, 918, 630],
       [921, 929, 384],
       [346, 399, 205]])

In [ ]:
# big = sales > 700
# sales = sales[big]
# sales

In [ ]:
small = sales < 300
sales[small] = 0
sales

array([[  0, 632, 546,   0, 976],
       [568,   0, 535, 413, 352],
       [874, 918, 630,   0, 312],
       [921, 929, 384, 427,   0],
       [346, 399,   0, 692, 855],
       [588, 843, 566,   0,   0],
       [379, 687, 664, 553,   0]])

In [ ]:
nonzero = sales != 0

sales=sales[nonzero]
sales

array([632, 546, 976, 568, 535, 413, 352, 874, 918, 630, 312, 921, 929,
       384, 427, 346, 399, 692, 855, 588, 843, 566, 379, 687, 664, 553])

#**Last Class**

In [ ]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9,1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
# Sum of every row
b  = np.sum(s, axis=1)
# b == 45

for i in b:
  if i!=45:
    print('sudoku is not valid')
    break
else:
  print('Valid hai')


Valid hai


In [ ]:
# Sum of every column
np.sum(s, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    add = s[i:i+3, j:j+3]
    print(add.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
data.shape

(5, 3)

In [ ]:
data.mean()

np.float64(61.06666666666667)

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
data[0:, 1]

array([85, 92, 76, 65, 90])

In [ ]:
data[0:, 2].max()

np.int64(95)

In [ ]:
more = data[:, 1] > 90
data[more]

array([[19, 92, 88]])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
c = data[:, 1] + 5
c

array([90, 97, 81, 70, 95])

In [ ]:
age = data[:, 0] < 19
print(data[age])

[[18 85 78]
 [17 76 95]
 [18 65 70]]


In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
math = data[:, 1].mean()
science = data[:, 2].mean()
math, science

(np.float64(81.6), np.float64(83.2))

In [ ]:
marks = (data[:, 1] >= 80) & (data[:, 2] >= 80)
data[marks]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# data[:,2][data[:, 2] < 75] = 0
# data

# n = data[:, 2] < 75
# data[:, 2][n] = 0
# data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

# **Final Questions**

In [ ]:
'''1.Create a NumPy array containing numbers from 1 to 15.

Print:
shape
size
dtype
ndim'''

n = np.arange(1,16)
n.shape, n.size, n.dtype, n.ndim

((15,), 15, dtype('int64'), 1)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
np.arange(5,51, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
np.linspace(0,100, 12)

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [ ]:
n = np.random.randint(1,101, 20)
n.max(), n.min(), n.mean()

(np.int64(93), np.int64(6), np.float64(49.35))

In [ ]:
n = np.random.randint(1,10, (4,5))
n

array([[5, 9, 8, 9, 3],
       [9, 4, 6, 5, 5],
       [3, 6, 5, 4, 1],
       [6, 7, 2, 4, 1]])

In [ ]:
n[:, 4]

array([9, 2, 1, 9])

In [ ]:
n[0]

array([8, 7, 8, 8, 9])

In [ ]:
n[1, 2]

np.int64(7)

In [ ]:
n = np.arange(1,25)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
n.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
n.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
n = np.random.randint(1,20, (5,5))
n

array([[19, 17, 19,  6,  4],
       [15, 19, 17, 11, 12],
       [12, 17,  5, 12,  7],
       [ 6, 14, 17,  2,  9],
       [ 4, 19, 15,  2, 17]])

In [ ]:
n[2, 2]

np.int64(5)

In [ ]:
for i in range(0,5):
    print(n[i, i])

19
19
5
2
17


In [ ]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[-1:-6:-1]

array([20, 19, 18, 17, 16])

In [ ]:
arr[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [ ]:
arr = np.random.randint(1,81, 15)
arr

array([64, 47,  6, 13,  7, 20, 43, 69, 49, 18, 72, 50, 52, 53, 32])

In [ ]:
n=  arr%2==0
arr[n]

array([64,  6, 20, 18, 72, 50, 52, 32])

In [ ]:
n = arr%2 !=0
arr[n]

array([47, 13,  7, 43, 69, 49, 53])

In [ ]:
n = arr > 50
arr[n]

array([64, 69, 72, 52, 53])

In [ ]:
arr

array([64, 47,  6, 13,  7, 20, 43, 69, 49, 18, 72, 50, 52, 53, 32])

In [ ]:
n = arr > 60
arr[n] = 60
arr

array([60, 47,  6, 13,  7, 20, 43, 60, 49, 18, 60, 50, 52, 53, 32])

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
a = np.random.randint(1, 20, 10)
b = np.random.randint(21,40, 10)
a,b

(array([10, 14,  6, 11,  3, 11,  9,  4, 14, 10]),
 array([22, 36, 34, 24, 31, 23, 29, 29, 24, 33]))

In [ ]:
a+b

array([32, 50, 40, 35, 34, 34, 38, 33, 38, 43])

In [ ]:
a-b

array([-12, -22, -28, -13, -28, -12, -20, -25, -10, -23])

In [ ]:
a*b

array([220, 504, 204, 264,  93, 253, 261, 116, 336, 330])

In [ ]:
a/b

array([0.45454545, 0.38888889, 0.17647059, 0.45833333, 0.09677419,
       0.47826087, 0.31034483, 0.13793103, 0.58333333, 0.3030303 ])

In [ ]:
a//b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a*5 - 10

array([40, 60, 20, 45,  5, 45, 35, 10, 60, 40])

In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [ ]:
a*b

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [ ]:
a@b

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [ ]:
a = np.arange(1,11)
b = np.arange(11,21)
a,b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]))

In [ ]:
a>b

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
b>a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
a ==b

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr = np.random.randint(1,50,(6,6))
arr

array([[45, 32, 34, 47, 21, 48],
       [13,  9, 43, 37, 16, 43],
       [29, 12, 30, 23, 36,  3],
       [47, 25, 21, 19, 47,  2],
       [33, 37, 15, 41, 30, 10],
       [39, 27, 25, 36, 38,  5]])

In [ ]:
np.sum(arr, axis = 1)

array([227, 161, 133, 161, 166, 170])

In [ ]:
np.sum(arr, axis=0)

array([206, 142, 168, 203, 188, 111])

In [ ]:
np.sum(arr)

np.int64(1018)

In [ ]:
arr = np.random.randint(1,100, (5,5))
arr

array([[30, 56, 13,  3, 88],
       [86, 89, 24, 62,  8],
       [58, 15, 64, 47, 81],
       [32, 31, 42, 89, 25],
       [24, 92, 46, 94, 94]])

In [ ]:
less = arr < 30
arr[less] = 0
arr

array([[30, 56,  0,  0, 88],
       [86, 89,  0, 62,  0],
       [58,  0, 64, 47, 81],
       [32, 31, 42, 89,  0],
       [ 0, 92, 46, 94, 94]])

In [ ]:
high = arr > 80
arr[high] = 100
arr

array([[ 30,  56,   0,   0, 100],
       [100, 100,   0,  62,   0],
       [ 58,   0,  64,  47, 100],
       [ 32,  31,  42, 100,   0],
       [  0, 100,  46, 100, 100]])

In [ ]:
a = np.random.randint(0,101, (10,5))

In [ ]:
a

array([[35, 93, 40, 57,  8],
       [74, 12, 90,  9, 83],
       [60,  8, 46, 15, 45],
       [58, 79, 64, 31, 75],
       [40, 55, 65, 98, 57],
       [80, 10,  7, 49, 40],
       [ 5, 13, 52, 80, 90],
       [74, 74, 68,  4, 76],
       [99, 22, 39, 53, 18],
       [15, 35, 31, 87, 74]])

In [ ]:
a[3]

array([58, 79, 64, 31, 75])

In [ ]:
a[:, 1]

array([93, 12,  8, 79, 55, 10, 13, 74, 22, 35])

In [ ]:
np.mean(a, axis = 0 )

array([54. , 40.1, 50.2, 48.3, 56.6])

In [ ]:
np.max(a)

np.int64(99)

In [ ]:
a.max()

np.int64(99)

In [ ]:
a

array([[35, 93, 40, 57,  8],
       [74, 12, 90,  9, 83],
       [60,  8, 46, 15, 45],
       [58, 79, 64, 31, 75],
       [40, 55, 65, 98, 57],
       [80, 10,  7, 49, 40],
       [ 5, 13, 52, 80, 90],
       [74, 74, 68,  4, 76],
       [99, 22, 39, 53, 18],
       [15, 35, 31, 87, 74]])

In [ ]:
n = a < 35
np.count_nonzero(n)

15

In [ ]:
n = (a< 35).sum()
n

np.int64(15)

In [ ]:
count = np.sum(a < 35)
count

np.int64(15)

In [ ]:
great = a> 90
a[great]

array([93, 98, 99])

In [ ]:
n = a<35
a[n] = 0
a

array([[35, 93, 40, 57,  0],
       [74,  0, 90,  0, 83],
       [60,  0, 46,  0, 45],
       [58, 79, 64,  0, 75],
       [40, 55, 65, 98, 57],
       [80,  0,  0, 49, 40],
       [ 0,  0, 52, 80, 90],
       [74, 74, 68,  0, 76],
       [99,  0, 39, 53,  0],
       [ 0, 35,  0, 87, 74]])