In [ ]:
import numpy as np

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
s.sum()

np.int64(405)

In [ ]:
b = np.sum(s,axis=1)
b == 45   # Checking if all the rows sum is 45 or not...

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
# Anoother way for checking
for i in b:
    if i != 45:
        print("sudoko is not valid")
        break
else:
    print("valid")

valid


In [ ]:
c = np.sum(s,axis = 0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
for i in c:
    if i!= 45:
        print("Sudoko is not valid")
        break
else:
    print("valid")

valid


In [ ]:
abc = s[0:3,0:3]
abc

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
for i in range(0,9,3):
    for j in range(0,3,9):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45


In [ ]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])


In [ ]:
# Give shape
data.shape

(5, 3)

In [ ]:
# Take out the average
np.mean([data[:,0]])

np.float64(18.4)

In [ ]:
# Extract math mark of all student
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
# science highest mark ?
np.max(data[:,2])

np.int64(95)

In [ ]:
# Get details of the student who scored more than 90 in Math
data[data[:,1] > 90]

array([[19, 92, 88]])

In [ ]:
# Increase math mark of all students by 5
data[:,1] +5

array([90, 97, 81, 70, 95])

In [ ]:
# find how many students are younger than 19
len(data[data[:,0] < 19])   # we used len() because we need to count

3

In [ ]:
# calculate the avg marks in each subject, column-wise mean.
np.mean(data[:,1:], axis=0)

array([81.6, 83.2])

In [ ]:
# get data of students who scored atleast 80 in both subjects
data[ (data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# Replace all science marks less than 75 with 0
data[:,2][data[:,2] < 75] = 0   # so firstly we selected all science column that is data[:,2] and then we checked that in that is there any low marks
# less than 75
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])